apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pending-demo
  template:
    metadata:
      labels:
        app: pending-demo
    spec:
      containers:
      - name: stress
        image: nginx
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
