apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: insomnia-webhook
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: insomnia
    groupBy: ["alertname"]
    matchers:
      - name: insomnia
        value: "true"

  receivers:
    - name: insomnia
      webhookConfigs:
        - url: http://host.docker.internal:8080/alert
          sendResolved: true